apiVersion: v1
kind: Service
metadata:
  name: longhorn-np
  namespace: longhorn-system
spec:
  type: NodePort
  selector:
    app: longhorn-ui
  ports:
  - name: longhorn-ui
    port: 80
    targetPort: 80
    nodePort: 30999
