apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: default
  labels:
    name: registry
    app: registry
spec:
  nodeSelector:
    kubernetes.io/hostname: "kube5"
  containers:
  - name: registry
    image: registry:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
    volumeMounts:
    - name: registry-volume
      mountPath: /var/lib/registry
  volumes:
  - name: registry-volume
    hostPath:
      path: /data/registry
      type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30123

