apiVersion: v1
kind: Service
metadata:
  name: trino-nodeport
  namespace: bigdata
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/instance: trino
    app.kubernetes.io/name: trino
  ports:
  - port: 7778
    targetPort: 7778
    nodePort: 30808
