apiVersion: v1
kind: Pod
metadata:
  name: solr
  namespace: bigdata
  labels:
    name: solr
    app: solr
    dns: hdfs-subdomain
spec:
  hostname: solr
  subdomain: company
  containers:
  - name: solr
    image: solr:8.11.3-slim
    resources:
      limits:
        memory: "2G"
        cpu: "500m"
    volumeMounts:
    - name: solr-config
      mountPath: /opt/solr/server/solr/configsets/ranger_audits/conf/
    - name: ranger-data
      mountPath: /var/solr/data/
    command: ["/bin/bash", "-c"]
    args:
    - |
      solr-precreate ranger_audits /opt/solr/server/solr/configsets/ranger_audits/
  volumes:
  - name: solr-config
    configMap:
      name: solr-config
      defaultMode: 0777
  - name: ranger-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: solr-np
  namespace: bigdata
spec:
  type: NodePort
  selector:
    app: solr
  ports:
  - port: 8983
    targetPort: 8983
    nodePort: 30983

